version: '3.8'

services:
  sql-server:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "leadDB2024"
      ACCEPT_EULA: "Y"
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-Usa", "-PleadDB2024", "-Q", "select 1", "-d", "LeadManagementDB"]
      interval: 15s
      retries: 20
    ports:
      - "1433:1433"
    volumes:
      - sql-server-data:/var/opt/mssql

  api:
    container_name: lead-management-api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      sql-server:
        condition: service_healthy
    environment:
      - 'ConnectionStrings__DefaultConnection=Server=sql-server,1433;Database=LeadManagementDB;TrustServerCertificate=true;Encrypt=false;User Id=sa;Password=leadDB2024'
    ports:
      - "8080:8080"

volumes:
  sql-server-data: